# Enable C++ support
language: cpp
# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
#env:
#  global:
#      - secure: ""
# Download and install intel compiler and MPI
before_install:
# - wget -q 'https://raw.githubusercontent.com/nemequ/icc-travis/master/install-icc.sh'
# - ./install-icc.sh --components icc,mpi
 - sudo apt-get -qq update
# - sudo apt-get install -y g++-4.9
 - sudo apt-get install -y mpich
 - sudo apt-get install -y libboost-dev
 - sudo apt-get install -y libboost-serialization-dev
 - test -n $CC  && unset CC
 - test -n $CXX && unset CXX
# Build steps
script:
# - source ~/.bashrc
 - make MPICXX=mpic++ CXX=g++ -j
 - make MPICXX=mpic++ CXX=g++ test -j
 - ./testbin/test
 - mpirun -np 4 ./testbin/test
#Uninstall intel tools
#after_script:
#  - '[[ ! -z "${INTEL_INSTALL_PATH}" ]] && uninstall_intel_software'
